### ISSUE TITLE
Getting this error on 1.4.7

### ISSUE THREAD

**Issue by Rog360** [DiGitHubCap/LevelFlare#1]
1:54:28 AM [severe]  Error occurred while disabling LevelFlare v1.6 (Is it up to date?)
1:54:28 AM [javastacktrace] java.lang.NullPointerException
1:54:28 AM [javastacktrace]     at java.util.concurrent.LinkedBlockingQueue.offer(Unknown Source)
1:54:28 AM [javastacktrace]     at java.util.AbstractQueue.add(Unknown Source)
1:54:28 AM [javastacktrace]     at me.Hoot215.updater.AutoUpdaterQueue.add(AutoUpdaterQueue.java:46)
1:54:28 AM [javastacktrace]     at me.Hoot215.LevelFlare.LevelFlare.onDisable(LevelFlare.java:324)
1:54:28 AM [javastacktrace]     at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:219)
1:54:28 AM [javastacktrace]     at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:481)
1:54:28 AM [javastacktrace]     at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:400)
1:54:28 AM [javastacktrace]     at org.bukkit.plugin.SimplePluginManager.disablePlugins(SimplePluginManager.java:393)
1:54:28 AM [javastacktrace]     at org.bukkit.craftbukkit.v1_4_R1.CraftServer.disablePlugins(CraftServer.java:277)
1:54:28 AM [javastacktrace]     at net.minecraft.server.v1_4_R1.MinecraftServer.stop(MinecraftServer.java:351)
1:54:28 AM [javastacktrace]     at net.minecraft.server.v1_4_R1.MinecraftServer.run(MinecraftServer.java:458)
1:54:28 AM [javastacktrace]     at net.minecraft.server.v1_4_R1.ThreadServerApplication.run(SourceFile:849)

**Comment by DiGitHubCap** [comment]
Hm... I wasn't aware that LinkedBlockingQueue didn't permit null elements. The error is completely harmless, so don't worry about it, but thanks for informing me. I'll have it fixed in the next version.

**Comment by Rog360** [comment]
Thanks for your quick response and work on this... :)
